// mygamelist/src/components/shared/carousel/RenderCarouselItems.vue
<template>
    <div style='all: inherit;'>
    <Fragment v-if='carouselType === `video`'>
        <div 
            v-for='(game, index) in carouselItems'
            v-bind:item='game'
            v-bind:key='game.id'

            class='flex-col carousel-card video'
        >
            <div 
                :class='`flex-col carousel-card-content-wrapper ${
                    videoFocused === game.id && !carouselShiftAnimation
                        ? `focused` 
                        : ``
                } ${ 
                    index === centerVideoIndex 
                    ? `center`
                        : index < centerVideoIndex 
                            ? `left` 
                            : `right`
                }`' 
                @click='shiftCarousel($event)'
            >
                <!-- <HandleVideoFocusRendering 
                    { ...props }
                    game={ game }
                    id={ id }
                /> -->
                <!-- const HandleVideoFocusRendering = (props) => {
    const {        
        // helpers
        focusVideo,
        handleVideoLoad,
        setPlaying,
        
        // state objs
        carouselShiftAnimation,
        videoFocused,
        videoLoaded,
        preFocusIndex,
        id, 
        game
    } = props -->
        <template v-if='videoFocused === index'>
        <!-- render this when a thumbnail has been focused (clicked on) -->
            <div class='carousel-video-container' >
                <Spinner 
                    :style='` 
                        display: 
                            ${videoLoaded  ? `none` : `block`}
                    `'
                />
                <youtube 
                    :video-id="game.videos[0].video_id" 
                    :player-vars="playerVars" 
                    :ready='handleReady()'
                    :paused='handlePause()'
                    :playing='handlePlay()'
                />
                <!-- <ReactPlayer 
                    class='carousel-video-player'
                    url={`https://www.youtube.com/watch?v=${game.videos[0].video_id}`} 
                    onReady={ handleVideoLoad }	
                    onPause={ () => setPlaying(false) }
                    onPlay={ () => setPlaying(true) }
                    playing={ true }
                    muted={true}
                    controls
                    width='100%'
                    height='100%'
                /> -->
                <img 
                    class='carousel-card-img disable-select'
                    draggable='false'
                    :src="videoThumbnail(game)" 
                    alt='img'
                    :style='`
                        opacity: ${!videoLoaded 
                            ? `1`
                            : carouselShiftAnimation 
                                ? `1`
                                : `0`}
                    `'
                />    
                    <!-- maybe templat here -->
                    <div v-if='carouselShiftAnimation' class='carousel-play-img-wrapper'>
                        <img 
                            draggable='false'
                            class='carousel-play-img disable-select opacity-transition-play-icon'
                            :src='require("../../../resources/img/play.png")'
                            alt='img'
                        />
                    </div>
                <div :key='game.id' class='shadow-image-fix'></div>
            </div>
        </template>
        <template v-else>
            <div 
                @click='handleFocus(index)'
                class='carousel-video-container nofocus '
            >
                <img 
                    draggable={false}
                    :src='videoThumbnail(game)'
                    alt='img'
                    class='carousel-card-img disable-select'
                />

                <!-- If clicked before animation is completed: video is queued to focus. This check displays spinner to indicate video will load when animation is finished -->
                    <Spinner v-if='preFocusIndex === index' />
                    <div v-else class='carousel-play-img-wrapper'>
                        <img 
                            draggable='false'
                            class='carousel-play-img disable-select'
                            :src='require("../../../resources/img/play.png")'
                            alt='img'
                        />
                    </div>
                <div :key='game.id' class='shadow-image-fix'></div>
            </div>          
        </template>
                <JustTitle
                    :game='game'
                    :hideTitle='(videoFocused === index && playing)'
                />
                    <!-- :hideTitle='(videoFocused === id) && playing' -->

                <!-- (videoFocused === game.id && playing) true/false result for title display transistion -->
                <!-- if video is videoFocused, and currently playing pass true (dont display) -->
                <!-- if video is playing, dont hide title -->

            </div>
        </div>
    </Fragment>
    <Fragment v-else>
        <div 
            v-for='(game) in carouselItems'
            v-bind:item='game'
            v-bind:key='game.id'

            :class='`flex-col carousel-card ${carouselType}`'
        >
            <!-- <router-link class='flex-col carousel-card-content-wrapper'> -->
            <router-link class='flex-col carousel-card-content-wrapper' :to='`/game/${game.id}`'>
                <img 
                    v-if='game.cover'
                    class='carousel-card-img'
                    :src="imageUrl(game)"
                    alt='img'
                />
                <JustTitle v-if='carouselType === `smaller`' :game='game' :carouselType='carouselType'/>
                <div v-else class='flex carousel-card-metadata'>
                        <div class='flex-col carousel-card-metadata-left'>
                            <p class='carousel-card-title'>{{game.name}}</p>
                                <p v-if='game.genres' class='carousel-card-subtitle'>
                                    {{game.genres[0].name}}
                                </p> 
                        </div> 
                            <div v-if='game.rating' class='flex-col carousel-card-metadata-right'>
                                <p class='carousel-card-rating-text'>Score:</p>
                                <p class='carousel-card-rating'>
                                    {{(game.rating/10).toFixed(2)}}
                                </p>
                            </div>
                    </div>
            </router-link>
        </div>
    </Fragment>
    </div>
</template>


<script>
    import Spinner from './LoadingSpinner.vue'
    import JustTitle from './JustTitle.vue'
    import Fragment from '../../Fragment.vue'

    export default {
    name: 'RenderCarouselItems',
    components: {
        Spinner,
        JustTitle,
        Fragment
    },
    data() {
        return {
            playerVars: {
                autoplay: 1
            }
        }
    },
    props: {
        carouselType : {
            type: String,
            required: true,
        },
        carouselItems : {
            type: Array,
            required: true,
        },
        carouselShiftAnimation : {
            type: String,
        },
        centerVideoIndex : {
            type: Number
        },
        videoFocused : {
            type: Number
        },
        videoLoaded : {
            type: Boolean
        },
        playing : {
            type: Boolean
        },
        preFocusIndex : {
            type: Number
        },
       
    },
    methods: {
        handleReady() {
            this.$emit('handle-video-load')
        },
        handlePlay() {
            this.$emit('set-playing', true)
        },
        handlePause() {
            this.$emit('set-playing', false)
        },
        handleFocus(index) {
            this.$emit('focus-video', index)
        },
        shiftCarousel(e) {
            this.$emit('shift-carousel', e)
        },
        imageUrl(game) {
            return `https://images.igdb.com/igdb/image/upload/t_cover_big${this.carouselType === 'smaller' ? '' : '_2x'}/${game.cover.image_id}.jpg`
        },
        videoThumbnail(game) {
            return `https://img.youtube.com/vi/${game.videos[0].video_id}/hqdefault.jpg`
        }
    },
    created() {
        console.log(this.centerVideoIndex)
    },
}
</script>
<style>
    iframe {
        height: 100%;
        width: 100%;
    }
</style>

// mygamelist/src/components/shared/carousel/RenderCarouselItems.jsx
import React from 'react';
import ReactPlayer from 'react-player/youtube'
import Spinner from './LoadingSpinner.jsx'
import { Link } from 'react-router-dom'


export default (props) => {
    return (
        props.carouselType === 'video' 
            ? <RenderVideoCards {...props} />
            : <RenderGameCards 
                carouselType={props.carouselType} 
                carouselItems={props.carouselItems} 
            />
    )
}

const RenderVideoCards = (props) => {
    const {
        // carousel content
        carouselItems,
        
        // helpers
        shiftCarousel,
        
        // state objs
        carouselShiftAnimation,
        centerVideoIndex,
        videoFocused,
        playing,

    } = props

    return carouselItems.map((game, id) => (
        <div 
            key={game.id} 
            className={`flex-col carousel-card video`}
        >
            {/* 
            check image size, if not normal thumbnail size, use normal thumbnail
            light={ true }
            */}
            <div 
                className={`flex-col carousel-card-content-wrapper ${
                    videoFocused === id && !carouselShiftAnimation
                        ? 'focused' 
                        : ''
                } ${ 
                    id === centerVideoIndex 
                    ? 'center'
                        : id < centerVideoIndex 
                            ? 'left' 
                            : 'right'
                }`}
                onClick={shiftCarousel}
            >
                <HandleVideoFocusRendering 
                    { ...props }
                    game={ game }
                    id={ id }
                />
                <JustTitle
                    game={game}
                    // passing true/false result for title display transistion
                    // if video is videoFocused, and currently playing pass true (dont display)
                    hideTitle={(videoFocused === id && playing)}
                />
            </div>
        </div>
    ))
}
const RenderGameCards = (props) => {
    const {
        // carousel content
        carouselItems,

        // check for smaller carousel type displaying only title of item
        carouselType,
    } = props
    return carouselItems.map((game, id) => (
        <div 
            key={game.id} 
            className={`flex-col carousel-card ${carouselType}`}
        >
            <Link className='flex-col carousel-card-content-wrapper' to={`/game/${game.id}`}>
            {/* <div className='flex-col carousel-card-content-wrapper'> */}
                { game.cover 
                    ? <img 
                        className='carousel-card-img'
                        src={`https://images.igdb.com/igdb/image/upload/t_cover_big${carouselType === 'smaller' ? '' : '_2x'}/${game.cover.image_id}.jpg`} 
                        alt='img'
                    />
                    : ''
                }
                {carouselType === 'smaller' 
                    ? <JustTitle game={game} carouselType={carouselType}/>
                    : <div className='flex carousel-card-metadata'>
                        <div className='flex-col carousel-card-metadata-left'>
                            <p className='carousel-card-title'>{game.name}</p>
                            { game.genres && 
                                <p className='carousel-card-subtitle'>
                                    {game.genres[0].name}
                                </p> 
                            }
                        </div> 
                        {game.rating &&
                            <div className='flex-col carousel-card-metadata-right'>
                                <p className='carousel-card-rating-text'>Score:</p>
                                <p className='carousel-card-rating'>
                                    {(game.rating/10).toFixed(2)}
                                </p>
                            </div>
                        }
                    </div>
                }
            {/* </div> */}
            </Link>
        </div>
    ))
}

const JustTitle = (props) => (
    <div 
        className='flex carousel-custom-container'
        style={{
        // if video is playing, dont hide title
            opacity: props.hideTitle ? 0 : 1,
            visibility: props.hideTitle ? 'hidden' : 'visible',
        }}
    >
        <div 
            className='flex carousel-card-metadata'
        >
            {props.carouselType === 'smaller' 
                ? <p className='carousel-card-title'>{props.game.name}</p> 
                : <Link
                    className='carousel-card-title'
                    to={`/game/${props.game.id}`}
                >{props.game.name}</Link>
             }
        </div>
    </div>
)

const HandleVideoFocusRendering = (props) => {
    const {        
        // helpers
        focusVideo,
        handleVideoLoad,
        setPlaying,
        
        // state objs
        carouselShiftAnimation,
        videoFocused,
        videoLoaded,
        preFocusIndex,
        id, 
        game
    } = props

    if ( videoFocused === id ) {
    // render this when a thumbnail has been focused (clicked on)
        return (
            <div className={`carousel-video-container`} >
                <Spinner 
                    style={{ 
                        display: 
                        // dont display spinner after loaded
                            videoLoaded  ? 'none' : 'block'
                    }} 
                />
                <ReactPlayer 
                    className='carousel-video-player'
                    url={`https://www.youtube.com/watch?v=${game.videos[0].video_id}`} 
                    onReady={ handleVideoLoad }	
                    onPause={ () => setPlaying(false) }
                    onPlay={ () => setPlaying(true) }
                    playing={ true }
                    muted={true}
                    controls
                    width='100%'
                    height='100%'
                />
                <img 
                    className={`carousel-card-img .disable-select`}
                    draggable={false}
                    src={`https://img.youtube.com/vi/${game.videos[0].video_id}/hqdefault.jpg`}
                    // src={`https://img.youtube.com/vi/${game.videos[0].video_id}/maxresdefault.jpg`} 
 
                    alt='img'
                    style={{
                    // if video not loaded or carousel is in animation, display thumbnail, else show video iframe
                        opacity: !videoLoaded 
                            ? 1
                            : carouselShiftAnimation 
                                ? 1
                                : 0
                    }}
                />                        
                { carouselShiftAnimation && 
                    <div className='carousel-play-img-wrapper'>
                        <img 
                            draggable={false}
                            className='carousel-play-img disable-select opacity-transition-play-icon'
                            src={require("../../../resources/img/play.png")}
                            alt='img'
                        />
                    </div>
                }
                <div key={game.id} className='shadow-image-fix'></div>
            </div>
        )
    } else {
        return  (
            <div 
                onClick={() => {focusVideo(id)}}
                className={`carousel-video-container nofocus`} 
            >
                <img 
                    draggable={false}
                    src={`https://img.youtube.com/vi/${game.videos[0].video_id}/hqdefault.jpg`} 
                    // src={`https://img.youtube.com/vi/${game.videos[0].video_id}/maxresdefault.jpg`} 
                    alt='img'
                    className='carousel-card-img disable-select'
                />

                { preFocusIndex === id
                // If clicked before animation is completed: video is queued to focus. This check displays spinner to indicate video will load when animation is finished
                    ? <Spinner/>
                    : <div className='carousel-play-img-wrapper'>
                        <img 
                            draggable={false}
                            className='carousel-play-img disable-select'
                            src={require("../../../resources/img/play.png")}
                            alt='img'
                        />
                    </div>
                }
                <div  key={game.id} className='shadow-image-fix'></div>
            </div>
        )
    }
}
